### ISSUE TITLE
cacao 0.3.0 doesn't compile for iOS

### ISSUE THREAD

**Issue by Miha-Rozina** [ryanmcgrath/cacao#36] opened 2022-07-20 12:53 UTC
I get the following error after upgrading cacao to the latest version.

error[E0308]: mismatched types
   --> .../cacao-0.3.0/src/image/image.rs:211:26
    |
211 |                   false => {
    |  __________________________^
212 | |                     #[cfg(target_os = "macos")]
213 | |                     panic!("SFSymbols are only supported on macOS 11.0 and up.")
214 | |                 }
    | |_________________^ expected *-ptr, found `()`
    |
    = note: expected raw pointer `*mut Object`
                 found unit type `()`

**Comment by ryanmcgrath** [comment] 2022-08-17 23:17
Hmmm, are you trying to construct an `Image` here? At first I though this issue was a duplicate that'd be solved by #46, but now I suspect you're trying to do something that's not supported on iOS yet.

Have a code block I could glance at?

**Comment by ryanmcgrath** [comment] 2022-08-21 23:21
#49 should have fixed this, I think - curious if it takes care of your issue~

**Comment by ryanmcgrath** [comment] 2022-08-22 23:26
Closing this for now as I can't reproduce this - but if you (or anyone) can, feel free to comment and I can take another look~

**Closed as completed by ryanmcgrath** 2022-08-22 23:26 UTC

**Comment by Miha-Rozina** [comment] 2022-08-26 13:39
I think the problem was just me not noticing that with cacao 3+ you need to enable uikit feature for ios development.
